artifacts_root: artifacts

data_insgestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/abdulbari80/dataset/blob/main/ds_salary.zip
  local_data_file: artifacts/data_ingestion/ds_salary.zip
  unzip_dir: artifacts/data_ingestion

